# Generated by Django 5.0.6 on 2024-05-21 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('isactive', models.BooleanField(default=True, verbose_name='Active')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.master')),
                ('statename', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
            bases=('fees.master',),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.master')),
                ('Districtname', models.CharField(max_length=200, unique=True)),
                ('statename', models.ForeignKey(limit_choices_to='isactive', on_delete=django.db.models.deletion.CASCADE, to='fees.state')),
            ],
            options={
                'verbose_name_plural': 'Districts',
            },
            bases=('fees.master',),
        ),
    ]
