# Generated by Django 5.0.6 on 2024-05-21 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='statename',
            field=models.ForeignKey(limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='fees.state'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.master')),
                ('Companyname', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=1000)),
                ('phone_no', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=100)),
                ('Districtname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.district')),
            ],
            bases=('fees.master',),
        ),
    ]
