# Generated by Django 5.0.6 on 2024-05-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_alter_district_statename_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
    ]
