# Generated by Django 5.0.6 on 2024-05-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.master')),
                ('Qualificationname', models.CharField(max_length=200)),
            ],
            bases=('fees.master',),
        ),
    ]
