# Generated by Django 5.0.6 on 2024-05-21 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0006_alter_course_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.master')),
                ('studentname', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
            bases=('fees.master',),
        ),
    ]
