# Generated by Django 5.0.6 on 2024-05-21 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_course_duration'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Coursename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Districtname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.district'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Qualificationname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.qualification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='companyname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fees.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='statename',
            field=models.ForeignKey(default=1, limit_choices_to={'isactive': True}, on_delete=django.db.models.deletion.CASCADE, to='fees.state'),
            preserve_default=False,
        ),
    ]
