# Generated by Django 5.0.6 on 2024-05-22 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_alter_course_duration'),
        ('student', '0002_student_coursename_student_districtname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='receipt',
            fields=[
                ('master_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fees.master')),
                ('receiptno', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=100)),
                ('studentname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            bases=('fees.master',),
        ),
    ]
