# Generated by Django 5.0.6 on 2024-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='logo',
            field=models.ImageField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
